[package]
name = "breaktime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "4.0.0"
open = "2.1.3"
rand = "0.8.5"
directories-next = "2.0.0"  
